// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pjqrepepiyppmsiylhuk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBqcXJlcGVwaXlwcG1zaXlsaHVrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDA1ODA5OTQsImV4cCI6MjA1NjE1Njk5NH0.He1ZMstmBFzH9F8zje1E7IQF1jiwnvJneznmUREdIXI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);